---
title: "Final Project"
author: "Jonathan Sunkari"
date: "2023-03-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
library(readr)
library(janitor)
library(ggmap)
```

```{r}
lunar <- read_csv("lunar.csv")
solar <- read_csv("solar.csv")
```

```{r}
names(lunar)
names(solar)
```
```{r}
install.packages("shinydashboard")
library(shinydashboard)
```
## Cleaning Names
```{r}
solar_e <- janitor::clean_names(solar)
```
```{r}
names(solar_e)
```

```{r}
lunar_e <- janitor::clean_names(lunar)
```
```{r}
names(lunar_e)
```



## Converting Latitude and Longitude Coords
```{r}
lunar <- lunar_e %>% 
  separate(latitude, into=c("lat", "NS"), sep="(?<=[0-9])(?=[A-Za-z])") %>% 
  separate(longitude, into=c("long", "EW"), sep="(?<=[0-9])(?=[A-Za-z])") %>% 
  mutate(lat_num = as.numeric(lat)) %>% 
  mutate(long_num = as.numeric(long)) %>% 
  mutate(latitude_value = ifelse(NS=="N", lat_num, -lat_num)) %>% 
  mutate(longitude_value = ifelse(EW=="E", long_num, -long_num)) 
lunar %>%
    select(latitude_value, longitude_value)
```
```{r}
solar <- solar_e %>% 
  separate(latitude, into=c("lat", "NS"), sep="(?<=[0-9])(?=[A-Za-z])") %>% 
  separate(longitude, into=c("long", "EW"), sep="(?<=[0-9])(?=[A-Za-z])") %>% 
  mutate(lat_num = as.numeric(lat)) %>% 
  mutate(long_num = as.numeric(long)) %>% 
  mutate(latitude_value = ifelse(NS=="N", lat_num, -lat_num)) %>% 
  mutate(longitude_value = ifelse(EW=="E", long_num, -long_num))
solar %>%
    select(latitude_value, longitude_value)
```

## Convert Catalog Number to a Numeric
```{r}
solar$catalog_number_num <- as.numeric(solar$catalog_number)
```
```{r}
lunar$catalog_number_num <- as.numeric(lunar$catalog_number)
```



```{r}
naniar::miss_var_summary(solar)
```
```{r}
naniar::miss_var_summary(lunar)
```



# Separating years out

Change Calendar Date Variable to Date Type
```{r}
class("calendar_date")
```

```{r}
lunar_dates <- lunar %>% 
  filter(!grepl("^-", calendar_date)) %>% 
  mutate(date = as.Date(calendar_date, format = "%Y %B %e")) %>% 
  select(!c(calendar_date)) %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         day = lubridate::day(date))
```
```{r}
solar_dates <- solar %>% 
  filter(!grepl("^-", calendar_date)) %>% 
  mutate(date = as.Date(calendar_date, format = "%Y %B %e")) %>% 
  select(!c(calendar_date)) %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         day = lubridate::day(date))
```


```{r}
lat <- c(-80, 80)
long <- c(-180, 180)
bbox <- make_bbox(long, lat, f=0.05)
map <- get_map(bbox, maptype = "toner-lite", source = "stamen")
```

```{r}
new_lunar <- lunar %>%
  filter(catalog_number=="00001"|catalog_number=="00002"|catalog_number=="00003"|catalog_number=="00004")

ggmap(map) + 
    geom_point(data=new_lunar, aes(longitude_value, latitude_value), size=0.4) +
    labs(x= "Longitude", y= "Latitude", title="Eclipse Locations")
```

```{r}
ggmap(map) + 
      geom_point(data=lunar, aes(longitude_value, latitude_value), size=0.04) +
      labs(x= "Longitude", y= "Latitude", title="Eclipse Locations")
```


```{r}
## Bare bones Dashboard shiny app 

library(shiny)

ui <- dashboardPage(
  dashboardHeader(title = "Peak Viewing Locations for Eclipses"),
  dashboardSidebar(title="Eclipse Selections", 
                   textInput("x", "Select Year", "input a year from 0-3000"),
                   selectInput("y", "Solar or Lunar Eclipses:", choices=c("Solar", "Lunar"), selected = "Solar"),
                   conditionalPanel(condition = "input.y == 'Solar'", radioButtons(
                     "z", label = "Which Type of Solar Eclipse", choices = c("Total", "Partial", "Annular", "Hybrid", "All Types"), selected = "All Types")
                    ),
                   conditionalPanel(condition = "input.y == 'Lunar'", radioButtons(
                     "a", label="Which Type of Lunar Eclipse", choices = c("Total", "Penumbral", "Partial", "All Types"), selected = "All Types")
                   )
                   ),
  dashboardBody(plotOutput("map", width = "600px", height = "700px"))
  
)

server <- function(input, output, session) {
  output$map <- renderPlot({
    new_lunar2 <- lunar_dates %>%
      filter(year == input$x)
    new_solar2 <- solar_dates %>%
      filter(year==input$x)
    # Defining Solar Eclipse Sub-types 
    annular_solar <- new_solar2 %>% filter(grepl("A", eclipse_type))
    partial_solar <- new_solar2 %>% filter(grepl("P", eclipse_type))
    total_solar <- new_solar2 %>% filter(eclipse_type=="T" | eclipse_type=="Ts" |eclipse_type=="Tm" | eclipse_type=="Tn" | eclipse_type=="T-" | eclipse_type=="T+")
    hybrid_solar <- new_solar2 %>% filter(grepl("H", eclipse_type))
    # Defining Lunar Eclipse Sub-types
    total_lunar <- new_lunar2 %>% filter(eclipse_type=="T" | eclipse_type=="T+" | eclipse_type=="T-")
    penumbral_lunar <- new_lunar2 %>% filter(grepl("N", eclipse_type))
    partial_lunar <- new_lunar2 %>% filter(grepl("P", eclipse_type))
    if (input$y == "Lunar") {
      if (input$a == "Total") {
        ggmap(map) + 
        geom_point(data=total_lunar, aes(longitude_value, latitude_value, color=month), size=4) +
        labs(x= "Longitude", y= "Latitude", title="Total Lunar Eclipse Locations")
      }
      else if (input$a == "Partial") {
        ggmap(map) + 
        geom_point(data=partial_lunar, aes(longitude_value, latitude_value, color=month), size=4) +
        labs(x= "Longitude", y= "Latitude", title="Partial Lunar Eclipse Locations")
      }
      else if (input$a == "Penumbral") {
        ggmap(map) + 
        geom_point(data=penumbral_lunar, aes(longitude_value, latitude_value, color=month), size=4) +
        labs(x= "Longitude", y= "Latitude", title="Penumbral Lunar Eclipse Locations")
      } else {
        ggmap(map) + 
        geom_point(data=new_lunar2, aes(longitude_value, latitude_value, color=month), size=4) +
        labs(x= "Longitude", y= "Latitude", title="All Lunar Eclipse Locations")
      }
    } else {
        if (input$z == "Annular") {
          ggmap(map) +
            geom_point(data=annular_solar, aes(longitude_value, latitude_value, color=month), size=4) +
            labs(x="Longitude", y="Latitude", title="Annular Solar Eclipse Locations")
        }
        else if (input$z == "Total") {
          ggmap(map) + 
          geom_point(data=total_solar, aes(longitude_value, latitude_value, color=month), size=4) +
          labs(x= "Longitude", y= "Latitude", title="Total Solar Eclipse Locations")
        }
        else if (input$z == "Partial") {
          ggmap(map) + 
          geom_point(data=partial_solar, aes(longitude_value, latitude_value, color=month), size=4) +
          labs(x= "Longitude", y= "Latitude", title="Partial Solar Eclipse Locations")
        }
        else if (input$z == "Hybrid") {
          ggmap(map) + 
          geom_point(data=hybrid_solar, aes(longitude_value, latitude_value, color=month), size=4) +
          labs(x= "Longitude", y= "Latitude", title="Hybrid Solar Eclipse Locations")
        } else {
          ggmap(map) + 
          geom_point(data=new_solar2, aes(longitude_value, latitude_value, color=month), size=4) +
          labs(x= "Longitude", y= "Latitude", title="All Solar Eclipse Locations")
        }
      
    }
      })
    }
shinyApp(ui, server)
```

- input for lunar vs solar (DONE)
- input for type of eclipse
- make input for range of years
- make input for user typing a specific year (DONE)




```{r}
## Trying to Personalize Shiny App with CSS
library(shiny)

ui <- fluidPage(
  tags$head(
    includeCSS("style.css"),
  ),
  tags$div(
    tags$link(rel = "stylesheet", type = "text/css", href = "style.css"),
    h1("Eclipse Analysis"),
    hr(),
    #p(strong("bold font "), em("italic font")),
    #p(code("code block")),
    #a(href="http://www.google.com", "link to Google"),
  selectInput("x", "Select Catalog Number", choices = c("00001", "00002", "00003", "00004"),
              selected = "00001"),
  #sliderInput("pointsize", "Select the Point Size", min = 0.5, max = 3, value = 1, step = 0.5),
  plotOutput("plot", width = "500px", height = "400px")
  )
)
server <- function(input, output, session) {
  output$plot <- renderPlot({
  ggplot(lunar, aes_string(x = input$x, y = Gamma)) +
      geom_col(alpha=0.8)
  })
}

shinyApp(ui, server)
```

