---
title: "eclipse_project"
output: html_document
date: "2023-03-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(skimr)
library(naniar)
library(here)
library(gtools)
library(RColorBrewer)
library(paletteer)
library(ggthemes)
library(shiny)
library(shinydashboard)
library(ggmap)
```

## Loading the Data
```{r}
getwd()
```

data website: https://www.kaggle.com/datasets/nasa/solar-eclipses

```{r}
solar_eclipse <- read_csv("/Users/ksricket/Desktop/Astro_Project_BIS15L/NASA lunar and solar eclipses/solar.csv")
```
```{r}
lunar_eclipse <- read_csv("/Users/ksricket/Desktop/Astro_Project_BIS15L/NASA lunar and solar eclipses/lunar.csv")
```

```{r}
solar_eclipse <- read_csv(here("NASA lunar and solar eclipses", "solar.csv"))
```



## Cleaning Names
```{r}
solar_e <- janitor::clean_names(solar_eclipse)
```
```{r}
names(solar_e)
```

```{r}
lunar_e <- janitor::clean_names(lunar_eclipse)
```
```{r}
names(lunar_e)
```



## Exploring
```{r}
glimpse(solar_e)
```

```{r}
glimpse(lunar_e)
```

## Variable Meanings:

#### Key to Catalog of Lunar Eclipses:
https://eclipse.gsfc.nasa.gov/LEcat5/LEcatkey.html

##### Key to Catalog of Solar Eclipses:
https://eclipse.gsfc.nasa.gov/SEcat5/SEcatkey.html



## Converting Latitude and Longitude Coords
```{r}
lunar <- lunar_e %>% 
  separate(latitude, into=c("lat", "NS"), sep="(?<=[0-9])(?=[A-Za-z])") %>% 
  separate(longitude, into=c("long", "EW"), sep="(?<=[0-9])(?=[A-Za-z])") %>% 
  mutate(lat_num = as.numeric(lat)) %>% 
  mutate(long_num = as.numeric(long)) %>% 
  mutate(latitude_value = ifelse(NS=="N", lat_num, -lat_num)) %>% 
  mutate(longitude_value = ifelse(EW=="E", long_num, -long_num)) 
lunar %>%
    select(latitude_value, longitude_value)
```
```{r}
solar <- solar_e %>% 
  separate(latitude, into=c("lat", "NS"), sep="(?<=[0-9])(?=[A-Za-z])") %>% 
  separate(longitude, into=c("long", "EW"), sep="(?<=[0-9])(?=[A-Za-z])") %>% 
  mutate(lat_num = as.numeric(lat)) %>% 
  mutate(long_num = as.numeric(long)) %>% 
  mutate(latitude_value = ifelse(NS=="N", lat_num, -lat_num)) %>% 
  mutate(longitude_value = ifelse(EW=="E", long_num, -long_num))
solar %>%
    select(latitude_value, longitude_value)
```

## Convert Catalog Number to a Numeric
```{r}
solar$catalog_number_num <- as.numeric(solar$catalog_number)
```
```{r}
lunar$catalog_number_num <- as.numeric(lunar$catalog_number)
```


## Mapping Framework
```{r}
lunar %>% 
  select(latitude_value, longitude_value) %>% 
  summary()
```
```{r}
lat_l <- c(-70, 70)
long_l <- c(-180, 180)
bbox_l <- make_bbox(long_l, lat_l, f=0.05)
```
```{r}
map_l <- get_map(bbox_l, maptype = "terrain", source = "stamen")
```
```{r}
ggmap(map_l)
```


```{r}
solar %>% 
  select(latitude_value, longitude_value) %>% 
  summary()
```
```{r}
lat_s <- c(-80, 80)
long_s <- c(-180, 180)
bbox_s <- make_bbox(long_s, lat_s, f=0.05)
```
```{r}
map_s <- get_map(bbox_s, maptype = "toner-lite", source = "stamen")
```
```{r}
ggmap(map_s)
```

## Mapping Tests
```{r}
ggmap(map_s)+
  geom_point(data=solar, aes(longitude_value, latitude_value))
```
```{r}
solar_filtered_dates1 <- solar %>% 
  arrange(catalog_number_num) %>% 
  head(n=10)
```
```{r}
ggmap(map_s)+
  geom_point(data=solar_filtered_dates1, aes(longitude_value, latitude_value))
```
```{r}
solar_filtered_dates2 <- solar %>% 
  filter(catalog_number_num==1)
```
```{r}
ggmap(map_s)+
  geom_point(data=solar_filtered_dates2, aes(longitude_value, latitude_value))
```
```{r}
solar_filtered_dates3 <- solar %>% 
  filter(catalog_number_num<=10 & catalog_number_num>=1)
```
```{r}
ggmap(map_s)+
  geom_point(data=solar_filtered_dates3, aes(longitude_value, latitude_value, color=calendar_date, size=central_duration))+
  labs(x="Latitude",
       y="Longitude",
       title="Solar Eclipses 1-10",
       color="Date",
       size="Central Duration")
# we would need to filter out all observations with NA central duration from the very beginning - before even deciding year groupings
```
```{r}
names(solar)
```

https://www.rebeccabarter.com/blog/2017-11-17-ggplot2_tutorial/ 







```{r}
naniar::miss_var_summary(solar)
```
```{r}
naniar::miss_var_summary(lunar)
```



## Filtering by Eclipse Type
```{r}
lunar_filtered_type <- lunar %>% 
  filter(eclipse_type=="T" | eclipse_type=="T+" |eclipse_type=="T-")
lunar_filtered_type 
# only shows the total lunar eclipses
```
```{r}
lunar %>% 
  filter(grepl("P", eclipse_type))
# only shows partial lunar eclipses
```
```{r}
lunar %>% 
  filter(grepl("N", eclipse_type))
# only shows penumbral lunar eclipses
```



```{r}
solar_filtered_type <- solar %>% 
  filter(eclipse_type=="T" | eclipse_type=="Ts" |eclipse_type=="Tm" | eclipse_type=="Tn" | eclipse_type=="T-" | eclipse_type=="T+")
solar_filtered_type
# total solar eclipses
```
```{r}
solar %>% 
  filter(grepl("P", eclipse_type))
# partial solar eclipses
```
```{r}
solar %>% 
  filter(grepl("A", eclipse_type))
# annular solar eclipses
```
```{r}
solar %>% 
  filter(grepl("H", eclipse_type))
# hybrid (annular/total) solar eclipses
```






## Other Data Explorations


```{r}
solar %>% 
  ggplot(aes(x=eclipse_type))+
  geom_bar()
```

```{r}
solar %>% 
  mutate(eclipse_type_broad = case_when(grepl("A", eclipse_type) ~ "A",
                                        grepl("H", eclipse_type) ~ "H",
                                        grepl("P", eclipse_type) ~ "P",
                                        grepl("T", eclipse_type) ~ "T")) %>% 
  ggplot(aes(x=eclipse_type_broad, fill=eclipse_type_broad))+
  geom_bar()+
  labs(title="Proportions of Solar Eclipse Types",
       x="Solar Eclipse Type",
       y="Count",
       fill="Solar Eclipse Type")+
  scale_fill_discrete(name = "Solar Eclipse Type", labels = c("Annular", "Hybrid (Annular and Total)", "Partial", "Total"))
```



```{r}
lunar %>% 
  ggplot(aes(x=eclipse_type))+
  geom_bar()
```
```{r}
lunar %>% 
  mutate(eclipse_type_broad = case_when(grepl("N", eclipse_type) ~ "N",
                                        grepl("P", eclipse_type) ~ "P",
                                        grepl("T", eclipse_type) ~ "T")) %>% 
  ggplot(aes(x=eclipse_type_broad, fill=eclipse_type_broad))+
  geom_bar()+
  labs(title="Proportions of Lunar Eclipse Types",
       x="Lunar Eclipse Type",
       y="Count",
       fill="Lunar Eclipse Type")+
  scale_fill_discrete(name = "Lunar Eclipse Type", labels = c("Penumbral", "Partial", "Total"))
```




```{r}
?case_when()
```




