---
title: "solar_first_look"
author: "Ananda Leia"
date: "2023-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Load these packages:
```{r}
library(tidyverse)
library(lubridate)
library(janitor)
library(dplyr)
```
Import the Solar Eclipse Dataset and clean names:
```{r}
solar <- read.csv("solar_lunar_data/solar.csv") %>% 
  clean_names()
solar
```

Change Calendar Date Variable to Date Type
```{r}
class("calendar_date")
```
```{r}
solar_dates <- solar %>% 
  filter(!grepl("^-", calendar_date)) %>% 
  mutate(date = as.Date(calendar_date, format = "%Y %B %e")) %>% 
  select(!c(calendar_date)) %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         day = lubridate::day(date))
solar_dates
```
```{r}
solar_dates %>% 
  filter(year <= 2023)
```


##Creating centuries column
```{r}
solar_cent <- solar_dates %>% 
  mutate(century_char = case_when(year >= 0 & year <100 ~ "1",
                                  year >= 100 & year <200 ~ "2",
                                  year >= 200 & year <300 ~ "3",
                                  year >= 300 & year <400 ~ "4",
                                  year >= 400 & year <500 ~ "5",
                                  year >= 500 & year <600 ~ "6",
                                  year >= 600 & year <700 ~ "7",
                                  year >= 700 & year <800 ~ "8",
                                  year >= 800 & year <900 ~ "9",
                                  year >= 900 & year <1000 ~ "10",
                                  year >= 1000 & year <1100 ~ "11",
                                  year >= 1100 & year <1200 ~ "12",
                                  year >= 1200 & year <1300 ~ "13",
                                  year >= 1300 & year <1400 ~ "14",
                                  year >= 1400 & year <1500 ~ "15",
                                  year >= 1500 & year <1600 ~ "16",
                                  year >= 1600 & year <1700 ~ "17",
                                  year >= 1700 & year <1800 ~ "18",
                                  year >= 1800 & year <1900 ~ "19",
                                  year >= 1900 & year <2000 ~ "20",
                                  year >= 2000 & year <2100 ~ "21",
                                  year >= 2100 & year <2200 ~ "22",
                                  year >= 2200 & year <2300 ~ "23",
                                  year >= 2300 & year <2400 ~ "24",
                                  year >= 2400 & year <2500 ~ "25",
                                  year >= 2500 & year <2600 ~ "26",
                                  year >= 2600 & year <2700 ~ "27",
                                  year >= 2700 & year <2800 ~ "28",
                                  year >= 2800 & year <2900 ~ "29",
                                  year >= 2900 & year <3000 ~ "30"))
solar_cent
```
```{r}
solar_cent$century = as.numeric(solar_cent$century_char)
```

```{r}
solar_cent %>% 
  ggplot(aes(x = century, fill = eclipse_type))+
  geom_bar()
```

```{r}
library(shiny)

ui <- fluidPage(
  selectInput("x", "Select Eclipse Type", choices = c("A", "A-", "A+", "Am", "An", "As", "H", "H2", "H3", "Hm", "P", "Pb", "Pe", "T", "T-", "T+", "Tm", "Tn", "Ts"), selected = "A")
  selectInput("y", "Select Century", choices)
  plotOutput ("plot")
)

server <- function(input, output, session) {
  output$plot <- renderPlot({
    ggplot(data = solar_cent, aes_string(x = eclipse_time, y = path_width_km))
  })
}

shinyApp(ui, server)
```
```{r}

```


```{r}
solar_cent %>% 
  ggplot(aes(x=))
```

https://sscc.wisc.edu/sscc/pubs/dwr/dates.html
http://jenrichmond.rbind.io/post/converting-characters-to-dates/
https://stackoverflow.com/questions/62928278/r-how-should-i-format-a-b-c-e-date-in-timevis
https://github.com/daattali/timevis/issues/99

